### ISSUE TITLE
APK Issue

### ISSUE THREAD

**Issue by conloi** [SAEEDStarv/xTGH#1]
Hello, sir.

I don't know how else I can reach out to you.

I would like to inform you that there's a problem with an APK.

More precisely, the ARMv7a version of TikTok has an issue: You cannot search anything, it will throw an error everytime where are supposed to appear the "search results".

![photo_2021-10-05_01-30-16](https://user-images.githubusercontent.com/93003259/138494836-799bf56d-dd2f-4251-be98-6692fc755ec3.jpg)

The ARM64v8a version of TikTok is fine.

**Comment by conloi** [comment]
@SAEEDStarv Unfortunately, I can't use v8 on my Nexus 5.

Search used to work well with the original APK, so it's most likely something wrong with the modded APK.

**Comment by conloi** [comment]
@SAEEDStarv I just installed your latest TikTok v22.0.4-Modified on my Nexus 5. I also installed your latest TikTok Plugin (v2.1.0).

The search is still not working... I get the error "You have searched the maximum number of searches today".

Changing the region and/or disabling/enabling "Discover Banner Ads" doesn't help.

So this is still an issue.

**Comment by SAEEDStarv** [comment]
Honestly i don't know what's the problem. Check if you haven't similar issue with original TikTok.
Also disable any DNS if you have one and try to create a new account and see if problem will be solve or not. This is not a problem with modification because you're the only one that reported this.
Also this is not a related issue with xTGH. If you want further guidance please join the telegram support group for TikTok Plugin:
https://t.me/TikTokPlugin

Thank you.
